version: '3.9'
name: artshare
services:
  db:
    container_name: artshare-database
    image: mysql:8.0.31
    restart: on-failure

    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TCP_PORT=${MYSQL_PORT}

    networks:
      default:
        aliases:
          - ${MYSQL_HOST}
    ports:
       - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    container_name: artshare-backend
    build:
      context: ../backend
      dockerfile: ../docker/backend.development.Dockerfile

    env_file:
      - .env

    ports:
      - 8080:8080

    volumes:  # Hot reload
      - ../backend:/app

  frontend:
    container_name: artshare-frontend
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.development.Dockerfile
    
    # env_file:
    #   - .env

    ports:
      - 3000:3000

    volumes:  # Hot reload
      - ../frontend:/app

volumes:
  mysql_data: