version: '3.3'
name: 'artshare'
services:
  db:
    container_name: artshare-database
    image: mysql:8.0.31
    platform: linux/x86_64
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    networks:
      default:
        aliases:
          - db
    ports:
       - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    container_name: artshare-backend
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile.development

    environment:
        - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
        - spring.datasource.url=jdbc:mysql://db:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
        - spring.datasource.username=${MYSQL_USER}
        - spring.datasource.password=${MYSQL_PASSWORD}
    ports:
      - 8080:8080

    # frontend:
    #   container_name: frontend
    #   build:
    #     context: ./frontend
    #     dockerfile: Dockerfile.development

    #   environment:

    #   ports:
    #     - 8080:8080

volumes:
  mysql_data: