# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:  
  pull_request:
    branches: 
      - develop
      - master
    paths:
      - 'frontend/**'
      - 'docker/**'
      - '.github/workflows/Frontend-CI.yml'


  workflow_call:


jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup the project
      working-directory: ./frontend
      run: |
        npm ci
    - name: Test the project
      working-directory: ./frontend
      run: npm run test
    - name: Build the project
      working-directory: ./frontend
      run: CI=false npm run build --if-present
