# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing Practice-app

on:
  push:
    branches: [ practice_app ]
  pull_request:
    branches: [ practice_app ]
  workflow_dispatch:
  

permissions:
  contents: read
  
env:
  FLASK_APP: app.py

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      working-directory: ./practice-app
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
        pip install -r requirements.txt
    - name: Lint code
      working-directory: ./practice-app
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Unit test
      working-directory: ./practice-app
      run: |
        python -m unittest
    - name: Test the Docker build
      working-directory: ./practice-app
      run: |
        docker build . --file Dockerfile --tag practice-app:$(date +%s)
